// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Product
{
	private final IMendixObject productMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.Product";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Price("Price"),
		Product_ProductGroup("MyFirstModule.Product_ProductGroup");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Product(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.Product"));
	}

	protected Product(IContext context, IMendixObject productMendixObject)
	{
		if (productMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.Product", productMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.Product");

		this.productMendixObject = productMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new Product(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Product create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.Product");
		return new myfirstmodule.proxies.Product(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Product.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Product initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.Product.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Product initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Product(context, mendixObject);
	}

	public static myfirstmodule.proxies.Product load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Product.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Product> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.Product> result = new java.util.ArrayList<myfirstmodule.proxies.Product>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.Product" + xpathConstraint))
			result.add(myfirstmodule.proxies.Product.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Price
	 */
	public final Double getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final Double getPrice(IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(Double price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(IContext context, Double price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * @return value of Product_ProductGroup
	 */
	public final myfirstmodule.proxies.ProductGroup getProduct_ProductGroup() throws CoreException
	{
		return getProduct_ProductGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of Product_ProductGroup
	 */
	public final myfirstmodule.proxies.ProductGroup getProduct_ProductGroup(IContext context) throws CoreException
	{
		myfirstmodule.proxies.ProductGroup result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Product_ProductGroup.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.ProductGroup.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Product_ProductGroup
	 * @param product_productgroup
	 */
	public final void setProduct_ProductGroup(myfirstmodule.proxies.ProductGroup product_productgroup)
	{
		setProduct_ProductGroup(getContext(), product_productgroup);
	}

	/**
	 * Set value of Product_ProductGroup
	 * @param context
	 * @param product_productgroup
	 */
	public final void setProduct_ProductGroup(IContext context, myfirstmodule.proxies.ProductGroup product_productgroup)
	{
		if (product_productgroup == null)
			getMendixObject().setValue(context, MemberNames.Product_ProductGroup.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Product_ProductGroup.toString(), product_productgroup.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return productMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Product that = (myfirstmodule.proxies.Product) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.Product";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
