// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class ProductGroupNodeData extends myfirstmodule.proxies.ProductTreeNodeData
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.ProductGroupNodeData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		NodeClass("NodeClass"),
		Key("Key"),
		ProductGroupNodeData_ProductGroup("MyFirstModule.ProductGroupNodeData_ProductGroup"),
		ProductTreeNodeData_ProductTreeWidgetData("MyFirstModule.ProductTreeNodeData_ProductTreeWidgetData"),
		ParentNode("MyFirstModule.ParentNode"),
		TreeViewNodeData_TreeViewWidgetData("MyFirstModule.TreeViewNodeData_TreeViewWidgetData");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public ProductGroupNodeData(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.ProductGroupNodeData"));
	}

	protected ProductGroupNodeData(IContext context, IMendixObject productGroupNodeDataMendixObject)
	{
		super(context, productGroupNodeDataMendixObject);
		if (!Core.isSubClassOf("MyFirstModule.ProductGroupNodeData", productGroupNodeDataMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.ProductGroupNodeData");
	}

	/**
	 * @deprecated Use 'new ProductGroupNodeData(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.ProductGroupNodeData create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.ProductGroupNodeData");
		return new myfirstmodule.proxies.ProductGroupNodeData(context, mendixObject);
	}

	/**
	 * @deprecated Use 'ProductGroupNodeData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.ProductGroupNodeData initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.ProductGroupNodeData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.ProductGroupNodeData initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ProductGroupNodeData(context, mendixObject);
	}

	public static myfirstmodule.proxies.ProductGroupNodeData load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ProductGroupNodeData.initialize(context, mendixObject);
	}

	/**
	 * @return value of ProductGroupNodeData_ProductGroup
	 */
	public final myfirstmodule.proxies.ProductGroup getProductGroupNodeData_ProductGroup() throws CoreException
	{
		return getProductGroupNodeData_ProductGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductGroupNodeData_ProductGroup
	 */
	public final myfirstmodule.proxies.ProductGroup getProductGroupNodeData_ProductGroup(IContext context) throws CoreException
	{
		myfirstmodule.proxies.ProductGroup result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductGroupNodeData_ProductGroup.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.ProductGroup.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductGroupNodeData_ProductGroup
	 * @param productgroupnodedata_productgroup
	 */
	public final void setProductGroupNodeData_ProductGroup(myfirstmodule.proxies.ProductGroup productgroupnodedata_productgroup)
	{
		setProductGroupNodeData_ProductGroup(getContext(), productgroupnodedata_productgroup);
	}

	/**
	 * Set value of ProductGroupNodeData_ProductGroup
	 * @param context
	 * @param productgroupnodedata_productgroup
	 */
	public final void setProductGroupNodeData_ProductGroup(IContext context, myfirstmodule.proxies.ProductGroup productgroupnodedata_productgroup)
	{
		if (productgroupnodedata_productgroup == null)
			getMendixObject().setValue(context, MemberNames.ProductGroupNodeData_ProductGroup.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductGroupNodeData_ProductGroup.toString(), productgroupnodedata_productgroup.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ProductGroupNodeData that = (myfirstmodule.proxies.ProductGroupNodeData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.ProductGroupNodeData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
