// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the Microflows for the MyFirstModule module

	public static myfirstmodule.proxies.ProductTreeWidgetData dS_ProductTree(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.DS_ProductTree", params);
			return result == null ? null : myfirstmodule.proxies.ProductTreeWidgetData.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static myfirstmodule.proxies.TreeViewWidgetData dS_SimpleDemo(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.DS_SimpleDemo", params);
			return result == null ? null : myfirstmodule.proxies.TreeViewWidgetData.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ProductGroupNode_Save(IContext context, myfirstmodule.proxies.ProductGroupNodeData _nodeData, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("nodeData", _nodeData == null ? null : _nodeData.getMendixObject());
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			Core.execute(context, "MyFirstModule.IVK_ProductGroupNode_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ProductNode_NewProduct(IContext context, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			Core.execute(context, "MyFirstModule.IVK_ProductNode_NewProduct", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ProductNode_Save(IContext context, myfirstmodule.proxies.ProductNodeData _nodeData, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("nodeData", _nodeData == null ? null : _nodeData.getMendixObject());
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			Core.execute(context, "MyFirstModule.IVK_ProductNode_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ProductNode_SelectParent(IContext context, myfirstmodule.proxies.ProductNodeData _nodeData, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("nodeData", _nodeData == null ? null : _nodeData.getMendixObject());
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			Core.execute(context, "MyFirstModule.IVK_ProductNode_SelectParent", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ProductTree_SaveNewProduct(IContext context, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			Core.execute(context, "MyFirstModule.IVK_ProductTree_SaveNewProduct", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_SelectProduct_Cheapest(IContext context, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			Core.execute(context, "MyFirstModule.IVK_SelectProduct_Cheapest", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_SelectProduct_First(IContext context, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			Core.execute(context, "MyFirstModule.IVK_SelectProduct_First", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<myfirstmodule.proxies.ProductTreeNodeData> jS_ProductTree_GetData(IContext context, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "MyFirstModule.JS_ProductTree_GetData", params);
			java.util.List<myfirstmodule.proxies.ProductTreeNodeData> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<myfirstmodule.proxies.ProductTreeNodeData>();
				for (IMendixObject obj : objs)
					result.add(myfirstmodule.proxies.ProductTreeNodeData.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void jS_ProductTree_OnClick(IContext context, myfirstmodule.proxies.ProductTreeNodeData _nodeData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("nodeData", _nodeData == null ? null : _nodeData.getMendixObject());
			Core.execute(context, "MyFirstModule.JS_ProductTree_OnClick", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<myfirstmodule.proxies.TreeViewNodeData> jS_SimpleDemo_GetData(IContext context, myfirstmodule.proxies.TreeViewWidgetData _treeViewWidgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("TreeViewWidgetData", _treeViewWidgetData == null ? null : _treeViewWidgetData.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "MyFirstModule.JS_SimpleDemo_GetData", params);
			java.util.List<myfirstmodule.proxies.TreeViewNodeData> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<myfirstmodule.proxies.TreeViewNodeData>();
				for (IMendixObject obj : objs)
					result.add(myfirstmodule.proxies.TreeViewNodeData.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<myfirstmodule.proxies.ProductTreeNodeData> sUB_ProductTree_GetData_Full(IContext context, myfirstmodule.proxies.ProductTreeWidgetData _productTreeWidgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("ProductTreeWidgetData", _productTreeWidgetData == null ? null : _productTreeWidgetData.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "MyFirstModule.SUB_ProductTree_GetData_Full", params);
			java.util.List<myfirstmodule.proxies.ProductTreeNodeData> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<myfirstmodule.proxies.ProductTreeNodeData>();
				for (IMendixObject obj : objs)
					result.add(myfirstmodule.proxies.ProductTreeNodeData.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void sUB_ProductTree_SelectProductNode(IContext context, myfirstmodule.proxies.Product _product, myfirstmodule.proxies.ProductTreeWidgetData _widgetData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			params.put("widgetData", _widgetData == null ? null : _widgetData.getMendixObject());
			Core.execute(context, "MyFirstModule.SUB_ProductTree_SelectProductNode", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}